language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-android-support
script:
- "./gradlew clean assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: a6nuh5ekOgOohtP86qCEaEArTt92bAKqc3rMZY+ZM5l5rHa1LOSxyH27O302Zpg0iyYM6YEinDSXk/hCML2Du5MT7F1IYER6bSlVFvCtgY9ylAuoQp/hwFFoh6ESCz383indTsNMUHOKL67fvi1ZTqzW60G/PZDs5AKyedpTJeZXxfpqoAYGOBZEaXYZIZAVHNbXWGoFN4bIXQD9u0zyP1WsENJ0n7dL2arpcPJ9u8no1oYPNaYftTHJ/ReQ+letcKqWj2TeELRvfx1GsavRnMLf07eKvGWm1pe5OUXKQoeznbRU1asBMgSHFrNw9rx+mWvYasW6r5PKG7PUwqXU5rdxuB8rLIHyOwupcdTKa9AMN+oUpxEhYr3pXtk0JqAMB+Y4OmpdLD37I+bfstQR3cxU8PJxYwfb+UHWyzdwMKuALRtIUVxqN+8fPy9fuHCzpmhGg4B8DjSnvZHxFP0Dgu45TsRjP1vsFKqSOT0D3GWXcP2JFm0qUnkuJc+360rVVqUOeAkUQjWko1eFOCUwL2aau6K86X5+/8rlpyt0HNdPHrMTALcyPzxuT36I8yXh9ip/QyNmul8+8Kj/QBSQr2VEZzQwcEn3q+Kn0Qf6mkGU/HuM3D7C9nkZ+k9VtjyjfBKETthLxXNhew4GleEy1NR1RS8eXRTkjRcQ4AHXA3o=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true