language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-android-support
script:
- "./gradlew clean assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: eoaYwFMm+untxJ3eMJuNtv9OSZlQ7hoWu1q4XesZnWVFpwr7Tf291GzEQIA83cbAEUJ0bVmKsB/NBimtmDNpE21nwqd06IYj8GvmrrhBO4wx+sx8IwAj8py4r8wIZuOPVc3PzJd8unhuaPpKB85I3kX9x802Co8aiOVHW3c9bH83h83JuGTwfN8oxDvjCgWKhrBafv70mOw3p6q5BrirznSXyUg7CEswPnkDnL1JksV/N0/XnNVaGuwRgcNepZqZsVoHjhgchXr5/DdnxEmRM+wbvQJ5eMEwqUfudz47Bjp0QZC7JA7Rn7+e3PbMQU8lPh0hDN3VPwDS+tcirT1rx8iSa83r2cACRqAQzTzes7y16v2aPaXf0sDJ8AegjK2IGAUAFQsm5e+XRe0LKp78M10JFqN5fjq0gkg14Z6c+UgiMZM0oJ/SUbo0VdfqAtqBhuXrNGAOgEz4qwHJOunbyzcJBuGfnFpKOseSczNyNecVsYSjMz2FB1BkjB8zUlJ+4s3eHzDZnbMJg0cDcgUhntZ3bZXX4hsKNLP/xFPScTHSgwTXxut5gqG0cR5ZAnzULc0w9/2XAZmbSc8fC0InyGUXQv+mWZV7+ZPftKoP30MzgwqFUGKRuU/eYcCjmoKVmO/65ud5S1NJPuPzGNKmlCUqZrEUAPwWe699NFltIZw=
  file_glob: true
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: duanhong169/GradientDrawableTuner
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_b9d263dc61f5_key -iv $encrypted_b9d263dc61f5_iv
  -in myshape.jks.enc -out myshape.jks -d
